services:
  database:
    image: postgres:16.3
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
      - TZ=America/Sao_Paulo
    ports:
      - '5432:5432'
    restart: unless-stopped

  nodeapi:
    build:
      context: ./express-apis
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
    depends_on:
      - nodeapi
    environment:
      - APISERVER_IP=nodeapi
    restart: unless-stopped
