services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'

  api:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_DATABASE=postgres
      - JWT_SECRET=token
    restart: always
    depends_on:
      - database
